from pathlib import Path
import re
root=Path('/mnt/data/v5_3_work')
old=(root/'ai.html').read_text()
sidebar=re.search(r'<aside class="sidebar">.*?</aside>',old,re.S).group(0)
# Keep AI Analyst active in all three pages, since they are sub-pages of AI Analyst.

styles='''\n/* v5.3 — AI Analyst sub-pages */\n.ai-subpage-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;margin-bottom:16px}.ai-breadcrumb{font-size:12px;color:var(--muted);margin-bottom:7px}.ai-breadcrumb a{color:#315efb;text-decoration:none}.ai-breadcrumb a:hover{text-decoration:underline}.ai-subpage-head h1{margin-bottom:5px}.ai-subpage-head p{margin:0;color:var(--muted);line-height:1.5}.ai-subpage-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:18px 0}.ai-subpage-card{min-height:275px;display:flex;flex-direction:column;position:relative}.ai-subpage-card .ai-option-note{margin-top:auto}.ai-subpage-card .btn{align-self:flex-start}.ai-subpage-card.active{border-color:#c7d2fe;box-shadow:0 0 0 2px #f0f3ff}.ai-subpage-card.disabled{opacity:.94}.ai-subpage-card h3{font-size:18px;margin:12px 0 8px}.ai-subpage-card p{color:var(--muted);line-height:1.55;font-size:13px}.ai-feature-list{margin:14px 0 0 19px;color:var(--muted);font-size:13px;line-height:1.7}.ai-feature-list li{margin-bottom:4px}.ai-flow{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:16px}.ai-flow-step{border:1px solid var(--line);border-radius:10px;padding:13px;background:#fff}.ai-flow-step b{display:block;margin-bottom:5px;font-size:12px}.ai-flow-step span{font-size:12px;color:var(--muted);line-height:1.45}.ai-security-callout{border-left:4px solid #315efb;background:#f7f9ff}.ai-disabled-label{display:inline-block;background:#f2f4f7;color:#687386;border-radius:999px;padding:4px 8px;font-size:10px;font-weight:800;letter-spacing:.4px}.ai-local-callout{border-left:4px solid #2b8a68;background:#f5fbf8}.ai-page-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:16px}.ai-provider-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:15px}.ai-provider{border:1px solid var(--line);border-radius:9px;padding:12px;background:#fafbfc}.ai-provider b{display:block;font-size:12px;margin-bottom:4px}.ai-provider span{font-size:11px;color:var(--muted)}\n@media(max-width:1050px){.ai-subpage-grid{grid-template-columns:1fr}.ai-flow{grid-template-columns:repeat(2,1fr)}.ai-provider-grid{grid-template-columns:1fr}}\n@media(max-width:650px){.ai-subpage-head{display:block}.ai-flow{grid-template-columns:1fr}.ai-page-actions .btn{width:100%;text-align:center}}\n'''
css=root/'css/style.css'
css.write_text(css.read_text()+styles)

def html(title, main, extra=''):
    return f'''<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CRM Intelligence — {title}</title><link rel="stylesheet" href="css/style.css"><script src="https://cdn.jsdelivr.net/npm/chart.js"></script><script src="https://cdn.jsdelivr.net/npm/xlsx/dist/xlsx.full.min.js"></script></head><body data-page="ai"><div class="app">{sidebar}<main class="main">{main}</main></div><script src="js/demo-data.js"></script><script src="js/app.js"></script>{extra}</body></html>'''

landing='''
<div class="ai-subpage-head"><div><div class="ai-breadcrumb"><a href="ai.html">AI Analyst</a> / Choose AI</div><h1>AI Analyst</h1><p><span class="badge">AI PREVIEW</span> Choose how you want AI to work with your business data.</p></div></div>
<div class="privacy">🔐 <b>Privacy-first AI.</b> We show you where your data goes before you choose an AI processing method.</div>
<div class="card ai-hero-card"><div class="ai-hero-copy"><span class="ai-status-pill">AI ANALYST</span><h3>Three ways to bring AI into CRM Intelligence</h3><p>Our goal is to make AI useful for business analysis without hiding the security and data-flow implications. Local AI is available today; the other two approaches are intentionally not enabled yet.</p></div></div>
<div class="ai-subpage-grid">
  <div class="card ai-subpage-card active"><div class="ai-option-top"><span class="ai-icon">🔒</span><span class="ai-live">AVAILABLE NOW</span></div><h3>Local AI — Maximum Privacy</h3><p>Run an AI model locally using Ollama. Your CRM analytics context stays on your computer and is sent to the local Ollama service rather than a public cloud AI provider.</p><div class="ai-option-note">Best choice when business-data privacy is the priority.</div><a class="btn primary" href="local-ai.html">Open Local AI →</a></div>
  <div class="card ai-subpage-card disabled"><div class="ai-option-top"><span class="ai-icon">🔑</span><span class="ai-disabled-label">NOT YET AVAILABLE</span></div><h3>Bring Your Own AI Key</h3><p>Use your own OpenAI, Gemini, Hugging Face or other provider credentials without giving those credentials to us.</p><div class="ai-option-note">Requires careful credential handling, provider-specific controls and security testing.</div><a class="btn" href="byok.html">Learn About BYOK →</a></div>
  <div class="card ai-subpage-card disabled"><div class="ai-option-top"><span class="ai-icon">☁️</span><span class="ai-disabled-label">NOT YET AVAILABLE</span></div><h3>Managed Cloud AI</h3><p>Use a managed AI service without creating or managing your own provider key.</p><div class="ai-option-note">Requires a secure backend/gateway, authentication, provider controls, cost management and cloud-data safeguards.</div><a class="btn" href="managed-cloud-ai.html">Learn About Managed AI →</a></div>
</div>
<div class="card"><h3>What AI Analyst is designed to help with</h3><div class="ai-provider-grid"><div class="ai-provider"><b>📊 Business analysis</b><span>Explain trends, performance changes and important commercial signals.</span></div><div class="ai-provider"><b>🎯 Prioritization</b><span>Surface customers, opportunities and risks that deserve management attention.</span></div><div class="ai-provider"><b>💬 Natural-language questions</b><span>Ask questions about your existing CRM analytics instead of manually searching dashboards.</span></div></div><div class="ai-flow"><div class="ai-flow-step"><b>1. Your data</b><span>Excel/CSV is processed in your browser.</span></div><div class="ai-flow-step"><b>2. Analytics</b><span>CRM Intelligence calculates the business context.</span></div><div class="ai-flow-step"><b>3. AI</b><span>Your selected AI method interprets that context.</span></div><div class="ai-flow-step"><b>4. Output</b><span>Answers, tables and interactive charts can be presented in the AI Analyst.</span></div></div></div>
<div class="card ai-security-callout"><h3>Why are two options disabled?</h3><p><b>We have deliberately enabled only Local AI in this MVP.</b> BYOK and managed cloud AI involve credentials, third-party data transmission, provider policies, security controls, cost management and additional technical infrastructure.</p><p>We would rather keep those capabilities disabled than expose your data or credentials through an incomplete integration.</p><p class="small">Interested in exploring either option with us? <a href="mailto:yogesh.kapadi.iimk@gmail.com?subject=MSME%20CRM%20Intelligence%20AI%20Exploration">Connect over email →</a></p></div>
'''
(root/'ai.html').write_text(html('AI Analyst',landing))

# Extract the local setup + workspace + modals and original inline script.
setup=re.search(r'<div class="card ai-option ai-option-active">.*?</div>\s*<div class="card ai-option ai-option-disabled">',old,re.S).group(0)
# remove trailing next-card opener from setup
setup=setup.rsplit('<div class="card ai-option ai-option-disabled">',1)[0]
workspace=re.search(r'<div class="card ai-workspace ai-chat-shell".*?</div>\s*<div class="card">',old,re.S).group(0)
workspace=workspace.rsplit('<div class="card">',1)[0]
# Get the first modal (open Ollama), not coming modal.
openmodal=re.search(r'<div class="modal-backdrop" id="aiOpenOllamaModal".*?</div>\s*</div>\s*',old,re.S)
openmodal=openmodal.group(0) if openmodal else ''
script=re.search(r'<script>\s*\(function\(\)\{.*?\}\)\(\);\s*</script>',old,re.S).group(0)
# Remove coming-modal-specific code from local page is unnecessary, but script references it safely. Keep modal only if wanted.
local_main=f'''
<div class="ai-subpage-head"><div><div class="ai-breadcrumb"><a href="ai.html">AI Analyst</a> / Local AI</div><h1>Local AI — Maximum Privacy</h1><p><span class="ai-live">AVAILABLE NOW</span> Run AI locally with Ollama.</p></div><div class="ai-page-actions"><a class="btn" href="ai.html">← AI Analyst</a></div></div>
<div class="privacy">🔒 <b>Maximum privacy.</b> CRM Intelligence sends the selected analytics context to Ollama running on your computer. It does not send that context to a cloud AI provider.</div>
{setup}
{workspace}
<div class="card ai-local-callout"><h3>What stays local?</h3><p>Your Excel/CSV remains in your browser. The AI request is sent to the Ollama service running on your computer. CRM Intelligence does not receive your Ollama credentials or your CRM file.</p><p class="small">Ollama must be installed and running before the connection can be established.</p></div>
<div class="card"><h3>Need help getting started?</h3><p>Install Ollama from the official Ollama website, open the application, then return here and click <b>Check Connection</b>. If the connection fails, the page will show troubleshooting guidance.</p><div class="ai-page-actions"><a class="btn" href="https://ollama.com/download" target="_blank" rel="noopener">Official Ollama Download ↗</a><a class="btn" href="mailto:yogesh.kapadi.iimk@gmail.com?subject=MSME%20CRM%20Intelligence%20Local%20AI%20Help">Email us for help</a></div></div>
{openmodal}
'''
# Ensure local page has coming modal if script expects it? Script guards mostly, but data-ai-coming absent. Fine.
(root/'local-ai.html').write_text(html('Local AI — Maximum Privacy',local_main,script))

byok='''
<div class="ai-subpage-head"><div><div class="ai-breadcrumb"><a href="ai.html">AI Analyst</a> / Bring Your Own AI Key</div><h1>Bring Your Own AI Key</h1><p><span class="ai-disabled-label">NOT YET AVAILABLE</span> Future BYOK architecture.</p></div><div class="ai-page-actions"><a class="btn" href="ai.html">← AI Analyst</a></div></div>
<div class="privacy">🔑 <b>BYOK means your provider account, your key and your responsibility.</b> We have not enabled this connection in the current MVP because credential handling needs to be designed and tested with exceptional care.</div>
<div class="card ai-security-callout"><h3>What BYOK would mean</h3><p>You would create and control an API key with your chosen AI provider. CRM Intelligence would use that credential to request AI analysis without us owning a shared provider key.</p><ul class="ai-feature-list"><li>Your API key should never be hard-coded into our public GitHub code.</li><li>Your key should never be sent to CRM Intelligence servers unless a future architecture explicitly requires it and is designed for secure secret handling.</li><li>Business information sent to a cloud provider would leave your computer, so the data flow would need to be explicit.</li><li>Provider-specific key restrictions, usage limits, billing controls and revocation procedures would need to be part of the design.</li></ul></div>
<div class="card"><h3>Why isn't BYOK enabled yet?</h3><p>A secure BYOK implementation is more than adding an API-key input box. It requires careful decisions around browser storage, credential exposure, provider APIs, content sent to the provider, error handling, abuse prevention and user education.</p><p><b>We would rather keep this disabled than expose your credentials or business data through an incomplete integration.</b></p></div>
<div class="card"><h3>Possible future providers</h3><div class="ai-provider-grid"><div class="ai-provider"><b>OpenAI</b><span>Future API integration — not enabled.</span></div><div class="ai-provider"><b>Google Gemini</b><span>Future API integration — not enabled.</span></div><div class="ai-provider"><b>Hugging Face / other providers</b><span>Future provider support subject to security review.</span></div></div></div>
<div class="card"><h3>Interested in BYOK?</h3><p>We can discuss your security requirements, provider preference and the right architecture before this capability is enabled.</p><div class="ai-page-actions"><a class="btn primary" href="mailto:yogesh.kapadi.iimk@gmail.com?subject=MSME%20CRM%20Intelligence%20BYOK%20Exploration">Connect over email</a><a class="btn" href="ai.html">Back to AI Analyst</a></div></div>
'''
(root/'byok.html').write_text(html('Bring Your Own AI Key',byok))

managed='''
<div class="ai-subpage-head"><div><div class="ai-breadcrumb"><a href="ai.html">AI Analyst</a> / Managed Cloud AI</div><h1>Managed Cloud AI</h1><p><span class="ai-disabled-label">NOT YET AVAILABLE</span> Future managed AI service.</p></div><div class="ai-page-actions"><a class="btn" href="ai.html">← AI Analyst</a></div></div>
<div class="privacy">☁️ <b>Managed Cloud AI would be the easiest user experience — but it has the highest infrastructure and data-governance responsibility for us.</b></div>
<div class="card ai-security-callout"><h3>What Managed Cloud AI would mean</h3><p>You would use AI without creating your own provider key. CRM Intelligence would operate a secure backend or AI gateway that authenticates users and communicates with an approved AI provider.</p><ul class="ai-feature-list"><li>Provider credentials would be held server-side, never in public browser code.</li><li>Requests would pass through a controlled backend/gateway rather than directly exposing a shared master key.</li><li>Authentication, authorization and rate limiting would be required.</li><li>Usage monitoring, quotas and cost controls would be required.</li><li>Cloud processing and third-party data handling would need to be clearly disclosed and governed.</li></ul></div>
<div class="card"><h3>Why isn't Managed Cloud AI enabled yet?</h3><p>Our current application is intentionally static and browser-first. A managed AI service would require additional infrastructure, security engineering, identity management, provider agreements, monitoring and careful treatment of customer business information.</p><p><b>We will not enable this simply by placing a provider API key in the GitHub Pages application.</b></p></div>
<div class="card"><h3>What the future experience could look like</h3><div class="ai-flow"><div class="ai-flow-step"><b>1. User asks</b><span>Question entered in the familiar AI Analyst interface.</span></div><div class="ai-flow-step"><b>2. Browser prepares context</b><span>CRM Intelligence sends only the information selected for AI analysis.</span></div><div class="ai-flow-step"><b>3. Secure gateway</b><span>Our backend authenticates and applies provider/security controls.</span></div><div class="ai-flow-step"><b>4. AI provider</b><span>The approved cloud model processes the request.</span></div></div></div>
<div class="card"><h3>Interested in exploring Managed Cloud AI?</h3><p>We can help evaluate the security, privacy, technical and commercial requirements before building this capability.</p><div class="ai-page-actions"><a class="btn primary" href="mailto:yogesh.kapadi.iimk@gmail.com?subject=MSME%20CRM%20Intelligence%20Managed%20Cloud%20AI%20Exploration">Connect over email</a><a class="btn" href="ai.html">Back to AI Analyst</a></div></div>
'''
(root/'managed-cloud-ai.html').write_text(html('Managed Cloud AI',managed))

# Update README with v5.3 page structure note.
readme=root/'README.md'
r=readme.read_text()
note='''\n\n## AI Analyst — v5.3\nThe AI Analyst is organized into three sub-pages under the existing **Data & Intelligence → AI Analyst** navigation item:\n- `local-ai.html` — **Local AI — Maximum Privacy** (enabled with Ollama)\n- `byok.html` — **Bring Your Own AI Key** (not yet enabled; security-first explanation)\n- `managed-cloud-ai.html` — **Managed Cloud AI** (not yet enabled; secure gateway architecture explanation)\n\nThe main `ai.html` page is the AI Analyst choice/overview page. BYOK and Managed Cloud AI are intentionally informational only until the required security architecture is implemented and tested.\n'''
if '## AI Analyst — v5.3' not in r:
    readme.write_text(r+note)
print('created', [x.name for x in [root/'ai.html',root/'local-ai.html',root/'byok.html',root/'managed-cloud-ai.html']])
